<?xml version="1.0"?>
<robot name="hercules" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="chassis_length" value="0.206" />
  <xacro:property name="chassis_width" value="0.135" />
  <xacro:property name="chassis_height" value="0.035" />

  <xacro:property name="wheel_radius" value="0.0425" />
  <xacro:property name="wheel_width" value="0.03" />

  <xacro:property name="wheelbase" value="0.16" />
  <xacro:property name="track" value="0.17" />
  <xacro:property name="wheel_vertical_offset" value="0.0" />

 <material name="black"><color rgba="0.15 0.15 0.15 1" /></material>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="green">
        <color rgba="0.22 1.0 0.07 1"/>
      </material>
    </visual>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.5"/>
        <inertia
          ixx="0.0024" ixy="0" ixz="0"
          iyy="0.0054" iyz="0"
          izz="0.0075"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
      <material>Gazebo/Green</material>
  </gazebo>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <!-- Example of where mesh definition goes (replaces cylinder) -->
        <!-- <mesh filename="package://hercules_description/meshes/Wheels.dae"/> -->
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia
          ixx="2.6326e-5" ixy="0" ixz="0"
          iyy="2.6326e-5" iyz="0"
          izz="4.5156e-5"/>
    </inertial>
  </link>

  <gazebo reference="front_right_wheel">
      <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="front_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin rpy="-1.5708 0 0" xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}"/>
  </joint>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia
          ixx="2.6326e-5" ixy="0" ixz="0"
          iyy="2.6326e-5" iyz="0"
          izz="4.5156e-5"/>
    </inertial>
  </link>

  <gazebo reference="front_left_wheel">
      <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="front_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin rpy="-1.5708 0 0" xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}"/>
  </joint>

  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia
          ixx="2.6326e-5" ixy="0" ixz="0"
          iyy="2.6326e-5" iyz="0"
          izz="4.5156e-5"/>
    </inertial>
  </link>

  <gazebo reference="back_right_wheel">
      <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="back_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin rpy="-1.5708 0 0" xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}"/>
  </joint>

  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black" />
    </collision>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia
          ixx="2.6326e-5" ixy="0" ixz="0"
          iyy="2.6326e-5" iyz="0"
          izz="4.5156e-5"/>
    </inertial>
  </link>

  <gazebo reference="back_left_wheel">
      <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="back_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin rpy="-1.5708 0 0" xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}"/>
  </joint>

  <!-- Bring in simulation data for Gazebo. -->
  <xacro:include filename="$(find hercules_description)/urdf/hercules.gazebo" />

</robot>